### ISSUE TITLE
Support Multiple Distribution URIs

### ISSUE THREAD

**Issue by vjkoskela** [rimerosolutions/maven-wrapper#10]
We started out using the Apache repository as specified in the example but this seemed to experience regular outages. One of the reasons we switched to Maven Wrapper was for more consistent builds across developer and build systems. The outages in the Apache repository were causing automated build failures which undermined our goals. 

We switched to the Ibiblio mirror and things improved. However, today the Ibiblio mirror seems to be experiencing problems. Instead of switching back to the Apache repository we would like to be able to specify multiple distribution URIs and only fail the build if none of these are accessible. 

If I get some time I will take a look at this myself, but I wanted to file the issue for tracking and to see if there were any other thoughts. In broad strokes the change would look like this:

- Extend [MavenWrapperMojo](https://github.com/rimerosolutions/maven-wrapper/blob/master/src/main/java/org/apache/maven/wrapper/MavenWrapperMojo.java) to _also_ support a list of distribution URIs.
- Convert [WrapperConfiguration](https://github.com/rimerosolutions/maven-wrapper/blob/master/src/main/java/org/apache/maven/wrapper/WrapperConfiguration.java) from a single base distribution to a list of base distributions. Encode the base distribution URIs into the wrapper properties file.
- Modify [WrapperExecutor](https://github.com/rimerosolutions/maven-wrapper/blob/master/src/main/java/org/apache/maven/wrapper/WrapperExecutor.java) to support reading multiple distribution URIs from the wrapper properties file.
- Modify [Installer](https://github.com/rimerosolutions/maven-wrapper/blob/master/src/main/java/org/apache/maven/wrapper/Installer.java) to support downloading from multiple distribution URIs.

**Comment by yveszoundi** [comment]
That would be nice to have. I'd also recommend having a corporate server hosting maven binaries, that is, if the related Maven projects are only internal.
