### ISSUE TITLE
Fails to run with Maven 3.3.1

### ISSUE THREAD

**Issue by TheLQ** [rimerosolutions/maven-wrapper#5]
When running with Maven 3.3.1 it exits with:

-Dmaven.multiModuleProjectDirectory system propery is not set. Check $M2_HOME environment variable and mvn script match

The only way to fix this is to add this to the Windows batch file:
set MAVEN_OPTS=%MAVEN_OPTS% -Dmaven.multiModuleProjectDirectory=%CD%

and this to the linux script:
MAVEN_OPTS="$MAVEN_OPTS -Dmaven.multiModuleProjectDirectory=$PWD"

**Comment by yveszoundi** [comment]
Thanks, I've seen similar issues reports on the internet such as 
- http://stackoverflow.com/questions/29137172/maven3-3-1-config-error-in-intellij-idea-14
- https://jira.codehaus.org/browse/MNG-5786
- https://jira.codehaus.org/browse/MNG-5767

It looks like moving forward the best way to handle it *might* be by supporting a `.mvn` folder as per recent proposals : 
- https://git-wip-us.apache.org/repos/asf?p=maven.git;a=commit;h=8ed9a1caa8890773b45c6c408a4e40acf4f4b0fd. 
- https://github.com/apache/maven/pull/40

I'll add your changes soon. Thanks for the bug report, as well as the workaround.

**Comment by yveszoundi** [comment]
After some quick local testing things seem ok. 

No MS windows testing was performed as I don't have a Windows machine around right now, if there are any issues, feel free to re-open this issue.

I'll start working on the Maven central upload.

**Comment by mmoayyed** [comment]
Problem still exists on Windows:
-Dmaven.multiModuleProjectDirectory system property is not set. Check $M2_HOME environment variable and mvn script match.
