### ISSUE TITLE
Fails to run when path has spaces

### ISSUE THREAD

**Issue by TheLQ** [rimerosolutions/maven-wrapper#7]
If the path has spaces (eg user name has spaces like c:\users\John Smith) the mvnw script will fail to run

Here's a test with the project dir having a space

lq@debiandev:~/space test$ ./mvnw clean build
Error: Could not find or load main class test

With this and Issue #5 is there any reason you can't use the the official batch and sh scripts or wrap them in some way?  That way this plugin would be future-proof and means Apache deals with the hard, weird environment support

**Comment by yveszoundi** [comment]
Thanks, I'll look at this problem soon. 

Indeed, it would be better to wrap the latest official scripts, I'm thinking about simple token substitutions with markers. I haven't done it yet for historical reasons and time constraints(evolving fork + regularly looking at which pieces are changing in Maven and how to make incorporate them nicely). 

I believe that issue #5 will require some additional changes in the future, it should just works.
I didn't see anything "final" about how the Maven team wants to handle it, I'm expecting further discussions requests related to design.
